#!/usr/bin/env python3

import roslib
import rospy

from health_monitor_node.main import HealthMonitorNode

NODE_NAME = 'health_monitor_node'
roslib.load_manifest(NODE_NAME)

if __name__ == '__main__':
    rospy.init_node(NODE_NAME)
    try:
        node = HealthMonitorNode()
    except rospy.ROSInterruptException:
        pass
